AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'config.ru'
  SuggestExtensions: false
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 150
